'use client';
import {useEffect,useState} from 'react';
import {Plus,Search,Pencil,Trash2,Flag,ShieldCheck,Pin,ArrowLeft,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Header,Picker,Toast,Icon,usePreferences} from '../shared';
import {initialData,type DirectoryData,type Listing,type Category,type Location} from '../../lib/data';
import {validateDirectory} from '../../lib/validation';
type Report={id:string;listingId:string;listingName:string;reason:string;details:string;status:string;createdAt:string};
type TaxEdit={kind:'categories'|'locations';item:Category|Location};
export default function Admin(){
const prefs=usePreferences(),{bn,t}=prefs;
const[data,setData]=useState<DirectoryData>(initialData),[reports,setReports]=useState<Report[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[q,setQ]=useState(''),[tab,setTab]=useState('listings'),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Listing|null>(null),[tax,setTax]=useState<TaxEdit|null>(null),[formError,setFormError]=useState(''),[deleting,setDeleting]=useState<{kind:'listings'|'categories'|'locations';id:string;name:string}|null>(null);
async function load(){setError('');try{const r=await fetch('/api/admin');const v=await r.json() as {data:DirectoryData;reports:Report[];error?:string};if(!r.ok)throw Error(v.error);setData(v.data);setReports(v.reports);setLoaded(true)}catch(e){setError((e as Error).message)}}
useEffect(()=>{void load()},[]);
useEffect(()=>{if(!message)return;const id=setTimeout(()=>setMessage(''),4000);return()=>clearTimeout(id)},[message]);
async function save(next:DirectoryData){next={...next,listings:next.listings.map(l=>({...l,bn:l.name,descriptionBn:l.description})),categories:next.categories.map(c=>({...c,bn:c.name})),locations:next.locations.map(l=>({...l,bn:l.name}))};validateDirectory(next);const r=await fetch('/api/admin',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const v=await r.json() as DirectoryData & {error?:string};if(!r.ok)throw Error(v.error);setData(v);setMessage(t('Changes saved','পরিবর্তন সংরক্ষিত হয়েছে'))}
function newListing(){setFormError('');setEditing({id:'contact-'+crypto.randomUUID(),name:'',bn:'',category:data.categories[0]?.id||'',location:'nationwide',number:'',description:'',descriptionBn:'',sample:true,verified:false,verifiedAt:'',source:'',logo:'',pinned:false})}
async function saveListing(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);setFormError('');try{const exists=data.listings.some(l=>l.id===editing.id);await save({...data,listings:exists?data.listings.map(l=>l.id===editing.id?editing:l):[...data.listings,editing]});setEditing(null)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
async function saveTax(e:React.FormEvent){e.preventDefault();if(!tax)return;setBusy(true);setFormError('');try{const rows=data[tax.kind];await save({...data,[tax.kind]:rows.some(c=>c.id===tax.item.id)?rows.map(c=>c.id===tax.item.id?tax.item:c):[...rows,tax.item]});setTax(null)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
async function remove(){if(!deleting)return;setBusy(true);setFormError('');try{if(deleting.kind==='categories'&&data.listings.some(l=>l.category===deleting.id)||deleting.kind==='locations'&&data.listings.some(l=>l.location===deleting.id))throw Error(t('Reassign associated listings before deleting.','মুছে ফেলার আগে সংশ্লিষ্ট তালিকাগুলো অন্য বিভাগ বা জেলায় সরান।'));await save({...data,[deleting.kind]:data[deleting.kind].filter(c=>c.id!==deleting.id)});setDeleting(null)}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
async function review(id:string,status:string){setBusy(true);setError('');try{const r=await fetch('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(!r.ok)throw Error((await r.json() as {error:string}).error);setReports(reports.map(v=>v.id===id?{...v,status}:v));setMessage(t('Report updated','রিপোর্ট আপডেট হয়েছে'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
const rows=data.listings.filter(l=>(l.name+' '+l.bn+' '+l.number).toLowerCase().includes(q.toLowerCase()));
const field=(key:keyof Listing,value:string|boolean)=>setEditing(l=>l?{...l,[key]:value}:l);
return <><Header prefs={prefs} admin/><main className="shell admin-shell" id="main"><a className="back-link" href="/"><ArrowLeft size={16}/>{t('Back to directory','ডিরেক্টরিতে ফিরুন')}</a><div className="admin-heading"><div><div className="eyebrow">{t('DIRECTORY MANAGEMENT','ডিরেক্টরি ব্যবস্থাপনা')}</div><h1>{t('Keep help within reach.','সহায়তার তথ্য হালনাগাদ রাখুন।')}</h1><p>{t('Manage contacts, verification, and community reports.','যোগাযোগ, যাচাই ও কমিউনিটির রিপোর্ট পরিচালনা করুন।')}</p></div><div className="admin-header-buttons"><button className="outline-button" onClick={async()=>{try{const r=await fetch("/api/login",{method:"DELETE"});if(!r.ok)throw Error("Could not sign out. Try again.");window.location.assign("/admin")}catch(e){setError((e as Error).message)}}}>Sign out</button><button className="outline-button" onClick={load} disabled={busy}><RefreshCw size={16}/>{t('Refresh','রিফ্রেশ')}</button></div></div>
{error&&<div className="notice warning" role="alert">{error}<button onClick={load}>{t('Retry','আবার চেষ্টা')}</button></div>}
{!loaded?<div className="stats">{[1,2,3].map(i=><Skeleton key={i} className="h-24"/>)}</div>:<><div className="stats"><div><Icon name="phone"/><span>{t('Directory contacts','ডিরেক্টরির যোগাযোগ')}</span><strong>{data.listings.length}</strong></div><div><ShieldCheck/><span>{t('Source verified','উৎস যাচাইকৃত')}</span><strong>{data.listings.filter(l=>l.verified&&!l.sample).length}</strong></div><div><Flag/><span>{t('Open reports','অমীমাংসিত রিপোর্ট')}</span><strong>{reports.filter(r=>r.status==='open').length}</strong></div></div>
<Tabs className="admin-tab-layout" value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="admin-tabs">{[['listings',t('Listings','তালিকা')],['categories',t('Categories','বিভাগ')],['locations',t('Locations','জেলা')],['reports',t('Reports','রিপোর্ট')]].map(([v,n])=><TabsTrigger key={v} value={v}>{n}</TabsTrigger>)}</TabsList>
<TabsContent value="listings"><div className="admin-toolbar"><label className="admin-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Find a contact…','যোগাযোগ খুঁজুন…')} aria-label={t('Search contacts','যোগাযোগ খুঁজুন')}/></label><button className="call-button" onClick={newListing}><Plus size={18}/>{t('Add listing','তালিকা যোগ করুন')}</button></div><div className="admin-contact-cards">{rows.map(l=><article className="admin-contact-card" key={l.id}><div className="admin-card-heading"><h3>{l.name}</h3>{l.pinned&&<Pin size={16} aria-label="Pinned contact"/>}</div><p>{data.categories.find(c=>c.id===l.category)?.name}</p><dl><div><dt>Number</dt><dd>{l.number}</dd></div><div><dt>Area</dt><dd>{data.locations.find(c=>c.id===l.location)?.name}</dd></div><div><dt>Verification</dt><dd><span className={'badge '+(!l.verified?'sample':'')}>{l.sample?'Sample':l.verified?'Verified':'Not verified'}</span>{l.verifiedAt&&<small>{l.verifiedAt}</small>}</dd></div></dl><div className="admin-card-actions"><button className="outline-button" aria-label={'Edit '+l.name} onClick={()=>{setEditing({...l});setFormError('')}}><Pencil size={18}/>Edit</button><button className="outline-button" aria-label={'Delete '+l.name} onClick={()=>{setDeleting({kind:'listings',id:l.id,name:l.name});setFormError('')}}><Trash2 size={18}/>Delete</button></div></article>)}</div><div className="table-wrap admin-listing-table"><Table><TableHeader><TableRow>{[t('Service','সেবা'),t('Number','নম্বর'),t('Area','জেলা'),t('Verification','যাচাই'),t('Actions','কার্যক্রম')].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(l=><TableRow key={l.id}><TableCell><b>{bn?l.bn:l.name}</b>{l.pinned&&<Pin size={13} className="inline-icon"/>}<small>{bn?data.categories.find(c=>c.id===l.category)?.bn:data.categories.find(c=>c.id===l.category)?.name}</small></TableCell><TableCell>{l.number}</TableCell><TableCell>{bn?data.locations.find(c=>c.id===l.location)?.bn:data.locations.find(c=>c.id===l.location)?.name}</TableCell><TableCell><span className={'badge '+(!l.verified?'sample':'')}>{l.sample?t('Sample','নমুনা'):l.verified?t('Verified','যাচাইকৃত'):t('Not verified','যাচাই করা হয়নি')}</span><small>{l.verifiedAt||'—'}</small></TableCell><TableCell><div className="row-actions"><button aria-label={t('Edit ','সম্পাদনা ')+l.name} onClick={()=>{setEditing({...l});setFormError('')}}><Pencil size={17}/></button><button aria-label={t('Delete ','মুছুন ')+l.name} onClick={()=>{setDeleting({kind:'listings',id:l.id,name:l.name});setFormError('')}}><Trash2 size={17}/></button></div></TableCell></TableRow>)}</TableBody></Table></div>{!rows.length&&<Empty><EmptyTitle>{t('No matching contacts','কোনো যোগাযোগ পাওয়া যায়নি')}</EmptyTitle></Empty>}</TabsContent>
{(['categories','locations'] as const).map(kind=><TabsContent value={kind} key={kind}><div className="admin-toolbar"><p>{data[kind].length} {kind==='categories'?t('categories','টি বিভাগ'):t('service areas','টি স্থান, সারাদেশসহ')}</p><button className="call-button" onClick={()=>{setTax({kind,item:{id:kind+'-'+crypto.randomUUID(),name:'',bn:'',...(kind==='categories'?{icon:'phone'}:{})}});setFormError('')}}><Plus size={18}/>{t('Add new','নতুন যোগ করুন')}</button></div><div className="taxonomy-grid">{data[kind].map(c=><div className="taxonomy-card" key={c.id}><div><b>{bn?c.bn:c.name}</b></div><div className="row-actions"><button aria-label={t('Edit ','সম্পাদনা ')+c.name} onClick={()=>{setTax({kind,item:{...c}});setFormError('')}}><Pencil size={17}/></button>{c.id!=='nationwide'&&<button aria-label={t('Delete ','মুছুন ')+c.name} onClick={()=>{setDeleting({kind,id:c.id,name:c.name});setFormError('')}}><Trash2 size={17}/></button>}</div></div>)}</div></TabsContent>)}
<TabsContent value="reports"><div className="admin-toolbar"><p>{t('Newest first · Up to 500 recent reports','নতুনগুলো আগে · সর্বশেষ ৫০০টি রিপোর্ট')}</p></div>{reports.length?<div className="report-list">{reports.map(r=><article className="report-card" key={r.id}><div><span className={'badge '+(r.status==='open'?'sample':'')}>{({open:t('Open','অমীমাংসিত'),resolved:t('Resolved','সমাধান হয়েছে'),dismissed:t('Dismissed','বাতিল')} as Record<string,string>)[r.status]}</span><small>{new Date(r.createdAt).toLocaleString(bn?'bn-BD':'en-GB')}</small></div><h3>{r.listingName}</h3><p><b>{({wrong:t('Wrong number','ভুল নম্বর'),unreachable:t('Unreachable','যোগাযোগ হচ্ছে না'),closed:t('Service closed','সেবা বন্ধ'),other:t('Other','অন্যান্য')} as Record<string,string>)[r.reason]}</b> · {r.details}</p><div className="row-actions"><button className="outline-button" disabled={busy||!data.listings.some(l=>l.id===r.listingId)} onClick={()=>{setEditing({...data.listings.find(l=>l.id===r.listingId)!});setFormError('')}}><Pencil size={15}/>{t('Edit listing','তালিকা সম্পাদনা')}</button><button className="outline-button" disabled={busy} onClick={()=>review(r.id,r.status==='open'?'resolved':'open')}>{r.status==='open'?t('Mark resolved','সমাধান হিসেবে চিহ্নিত'):t('Reopen','আবার খুলুন')}</button>{r.status!=='dismissed'&&<button className="outline-button" disabled={busy} onClick={()=>review(r.id,'dismissed')}>{t('Dismiss','বাতিল')}</button>}</div></article>)}</div>:<Empty className="empty-state"><ShieldCheck size={32}/><EmptyTitle>{t('No reports yet','এখনও কোনো রিপোর্ট নেই')}</EmptyTitle><EmptyDescription>{t('Community reports will appear here for review.','কমিউনিটির রিপোর্ট পর্যালোচনার জন্য এখানে দেখা যাবে।')}</EmptyDescription></Empty>}</TabsContent></Tabs></>}
<p className="results-footnote">{t('Administrator access is checked on the server. Only source-checked, non-sample contacts can be marked verified.','সার্ভারে অ্যাডমিন অনুমতি পরীক্ষা করা হয়। শুধু উৎস যাচাইকৃত প্রকৃত যোগাযোগ যাচাইকৃত হিসেবে চিহ্নিত করা যায়।')}</p></main><Toast message={message}/>
<Dialog open={!!editing} onOpenChange={v=>!v&&!busy&&setEditing(null)}><DialogContent className="form-dialog large-dialog"><DialogTitle>{data.listings.some(l=>l.id===editing?.id)?t('Edit listing','তালিকা সম্পাদনা'):t('Add listing','তালিকা যোগ করুন')}</DialogTitle><DialogDescription>{t('Use an official source before enabling verification. Sample numbers cannot be called.','যাচাই করতে অফিসিয়াল উৎস ব্যবহার করুন। নমুনা নম্বরে কল করা যাবে না।')}</DialogDescription>{editing&&<form onSubmit={saveListing}><div className="form-grid"><label>{t('Name','ইংরেজি নাম')}<input required maxLength={150} value={editing.name} onChange={e=>field('name',e.target.value)}/></label><label>{t('Category','বিভাগ')}<Picker label={t('Category','বিভাগ')} value={editing.category} onChange={v=>field('category',v)} options={data.categories.map(c=>({value:c.id,label:bn?c.bn:c.name}))}/></label><label>{t('Location','জেলা')}<Picker label={t('Location','জেলা')} value={editing.location} onChange={v=>field('location',v)} options={data.locations.map(c=>({value:c.id,label:bn?c.bn:c.name}))}/></label><label>{t('Phone number','ফোন নম্বর')}<input required maxLength={30} value={editing.number} onChange={e=>field('number',e.target.value)} placeholder="01XXX-XXXXXX"/></label><label>{t('Logo URL (HTTPS)','লোগোর লিংক (HTTPS)')}<input type="url" value={editing.logo} onChange={e=>field('logo',e.target.value)} placeholder="https://…"/></label><label>{t('Description','ইংরেজি বিবরণ')}<textarea maxLength={500} value={editing.description} onChange={e=>field('description',e.target.value)}/></label></div><div className="form-checks"><label><Checkbox checked={editing.sample} onCheckedChange={v=>setEditing({...editing,sample:v===true,verified:v?false:editing.verified,verifiedAt:v?'':editing.verifiedAt})}/>{t('Sample listing','নমুনা তালিকা')}</label><label><Checkbox checked={editing.pinned} onCheckedChange={v=>field('pinned',v===true)}/>{t('Pin to top','উপরে পিন করুন')}</label><label><Checkbox disabled={editing.sample} checked={editing.verified} onCheckedChange={v=>field('verified',v===true)}/>{t('Verified','যাচাইকৃত')}</label></div><div className="form-grid"><label>{t('Last verified date','সর্বশেষ যাচাইয়ের তারিখ')}<input type="date" required={editing.verified} max={new Date().toISOString().slice(0,10)} value={editing.verifiedAt} onChange={e=>field('verifiedAt',e.target.value)}/></label><label>{t('Verification source URL','যাচাইয়ের উৎসের লিংক')}<input type="url" required={editing.verified} value={editing.source} onChange={e=>field('source',e.target.value)} placeholder="https://…"/></label></div>{formError&&<p className="error" role="alert">{formError}</p>}<button className="call-button" disabled={busy}>{busy?t('Saving…','সংরক্ষণ হচ্ছে…'):t('Save listing','তালিকা সংরক্ষণ')}</button></form>}</DialogContent></Dialog>
<Dialog open={!!tax} onOpenChange={v=>!v&&!busy&&setTax(null)}><DialogContent className="form-dialog"><DialogTitle>{tax?.kind==='categories'?t('Manage category','বিভাগ পরিচালনা'):t('Manage location','স্থান পরিচালনা')}</DialogTitle><DialogDescription>{t('Choose a clear, easy-to-read name.','দুই ভাষায় ডিরেক্টরিতে নাম দেখা যাবে।')}</DialogDescription>{tax&&<form onSubmit={saveTax}><label>{t('Name','ইংরেজি নাম')}<input required maxLength={150} value={tax.item.name} onChange={e=>setTax({...tax,item:{...tax.item,name:e.target.value}})}/></label>{tax.kind==='categories'&&<label>{t('Icon','আইকন')}<Picker label={t('Icon','আইকন')} value={(tax.item as Category).icon} onChange={v=>setTax({...tax,item:{...tax.item,icon:v}})} options={['phone','ambulance','flame','shield','hospital','blood','wifi','zap','water','bus','bank','mobile','building'].map(v=>({value:v,label:v}))}/></label>}{formError&&<p className="error" role="alert">{formError}</p>}<button className="call-button" disabled={busy}>{t('Save changes','পরিবর্তন সংরক্ষণ')}</button></form>}</DialogContent></Dialog>
<AlertDialog open={!!deleting} onOpenChange={v=>!v&&!busy&&setDeleting(null)}><AlertDialogContent><AlertDialogTitle>{t('Delete ','মুছে ফেলুন ')}{deleting?.name}?</AlertDialogTitle><AlertDialogDescription>{t('This removes the item from the shared directory. Existing reports are retained.','এটি ডিরেক্টরি থেকে সরিয়ে দেবে। বিদ্যমান রিপোর্ট সংরক্ষিত থাকবে।')}</AlertDialogDescription>{formError&&<p role="alert" className="error">{formError}</p>}<div className="row-actions"><AlertDialogCancel disabled={busy}>{t('Cancel','বাতিল')}</AlertDialogCancel><button className="danger-button" disabled={busy} onClick={remove}>{busy?t('Deleting…','মুছে ফেলা হচ্ছে…'):t('Delete','মুছুন')}</button></div></AlertDialogContent></AlertDialog></>}






