'use client';
import {useEffect,useState} from 'react';
import {Phone,Moon,Sun,ArrowUpRight,LayoutGrid,Bookmark,Flame,ShieldCheck,HeartPulse,Hospital,Droplets,Wifi,Zap,Bus,Landmark,Smartphone,Building2,Ambulance,MessageSquare} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export function Icon({name,size=20}:{name:string;size?:number}){const C=({phone:Phone,flame:Flame,shield:ShieldCheck,heart:HeartPulse,hospital:Hospital,blood:Droplets,water:Droplets,wifi:Wifi,zap:Zap,bus:Bus,bank:Landmark,mobile:Smartphone,building:Building2,ambulance:Ambulance,grid:LayoutGrid} as Record<string,typeof Phone>)[name]||Phone;return <C size={size}/>}
export function usePreferences(){const[dark,setDark]=useState(false),[ready,setReady]=useState(false);
useEffect(()=>{try{const s=localStorage.getItem('dak-theme');setDark(s?s==='dark':matchMedia('(prefers-color-scheme: dark)').matches)}catch{}setReady(true)},[]);
useEffect(()=>{if(!ready)return;document.documentElement.lang='en';document.documentElement.classList.toggle('dark',dark);try{localStorage.setItem('dak-theme',dark?'dark':'light')}catch{}},[dark,ready]);return {bn:false,dark,setDark,t:(en:string,_unused?:string)=>en}}
export function LiveClock(){const[now,setNow]=useState<Date|null>(null);useEffect(()=>{setNow(new Date());const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);return <div className="live-clock" aria-label="Current time in Bangladesh"><time dateTime={now?.toISOString()}>{now?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dhaka',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}).format(now):'--:--:--'}</time><span>{now?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dhaka',weekday:'short',day:'numeric',month:'short'}).format(now):'Bangladesh time'} · Bangladesh</span></div>}
export function Header({prefs,saved=false,admin=false,forum=false}:{prefs:ReturnType<typeof usePreferences>;saved?:boolean;admin?:boolean;forum?:boolean}){const{dark,setDark}=prefs;return <><a href="#main" className="skip-link">Skip to content</a><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Phone size={25}/></span><b>Muksudpur<span>Directory</span></b></a><nav aria-label="Main navigation"><a className={!saved&&!admin&&!forum?'active':''} href="/">Directory</a><a className={saved?'active':''} href="/?saved=1">Saved numbers</a></nav><div className="header-actions"><button className="theme-button" onClick={()=>setDark(!dark)} aria-label={dark?'Use light mode':'Use dark mode'}>{dark?<Sun size={21}/>:<Moon size={21}/>}<span>{dark?'Light':'Dark'}</span></button><a href="/admin">Admin <ArrowUpRight size={17}/></a></div></header></>}
export function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={v=>onChange(v??'')}><SelectTrigger aria-label={label} className="picker"><SelectValue>{options.find(o=>o.value===value)?.label||label}</SelectValue></SelectTrigger><SelectContent alignItemWithTrigger={false}>{options.map(o=><SelectItem key={o.value} value={o.value} className="picker-item">{o.label}</SelectItem>)}</SelectContent></Select>}
export function MobileNav({saved=false,bn=false,forum=false}:{saved?:boolean;bn?:boolean;forum?:boolean}){return <nav className="mobile-nav" aria-label={bn?'মোবাইল নেভিগেশন':'Mobile navigation'}><a className={!saved&&!forum?'selected':''} href="/"><LayoutGrid size={21}/>{bn?'ডিরেক্টরি':'Directory'}</a><a href="/#emergency"><Phone size={21}/>{bn?'জরুরি':'Emergency'}</a><a className={saved?'selected':''} href="/?saved=1"><Bookmark size={21}/>{bn?'সংরক্ষিত':'Saved'}</a><a className={forum?'selected':''} href="/forum"><MessageSquare size={21}/>Community</a><a href="/admin"><ShieldCheck size={21}/>{bn?'অ্যাডমিন':'Admin'}</a></nav>}
export function Toast({message}:{message:string}){return <div className={'toast '+(message?'visible':'')} role="status" aria-live="polite">{message}</div>}




