import {createCipheriv,createDecipheriv,randomBytes,createHash} from 'node:crypto';
import {readFile,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
import type {DirectoryData} from './data';
export type Post={id:string;message:string;number:string;createdAt:string};
export type Report={id:string;listingId:string;listingName:string;reason:string;details:string;status:string;createdAt:string};
type PrivateData={reports:Report[];sessions:Record<string,number>;limits:Record<string,{count:number;expires:number}>};
export type State={directory:DirectoryData;posts:Post[];private:PrivateData};
type DiskState={version:1;directory:DirectoryData;posts:Post[];private:string|null};
export class StoreError extends Error {constructor(message:string,public status=503){super(message)}}
const file=path.join(process.cwd(),'data','directory.json');
const emptyPrivate=():PrivateData=>({reports:[],sessions:{},limits:{}});
function key(){const s=process.env.DATA_SECRET;if(!s||!/^[a-f0-9]{64}$/.test(s))throw new StoreError('Server secret is not configured.');return Buffer.from(s,'hex')}
function decode(d:DiskState):State{if(d.version!==1||!d.directory||!Array.isArray(d.posts))throw new StoreError('Directory file format is invalid.');let privateData=emptyPrivate();if(d.private){try{const b=Buffer.from(d.private,'base64'),c=createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));c.setAuthTag(b.subarray(12,28));privateData=JSON.parse(Buffer.concat([c.update(b.subarray(28)),c.final()]).toString('utf8'))}catch{throw new StoreError('Private data could not be opened. Check the server secret.')}}return {directory:d.directory,posts:d.posts,private:privateData}}
function encode(s:State){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv),encrypted=Buffer.concat([c.update(JSON.stringify(s.private),'utf8'),c.final()]);const text=JSON.stringify({version:1,directory:s.directory,posts:s.posts,private:Buffer.concat([iv,c.getAuthTag(),encrypted]).toString('base64')},null,2)+'\n';if(Buffer.byteLength(text)>750000)throw new StoreError('Directory file capacity reached. Contact the administrator.',507);return text}
function github(){return process.env.STORAGE_MODE==='github'}
function endpoint(){const repo=process.env.GITHUB_REPOSITORY,branch=process.env.GITHUB_BRANCH||'main';if(!repo||!/^[-\w.]+\/[-\w.]+$/.test(repo)||!process.env.GITHUB_TOKEN)throw new StoreError('GitHub storage is not configured.');return {url:'https://api.github.com/repos/'+repo+'/contents/data/directory.json',branch}}
async function gh(method:string,payload?:unknown){const {url,branch}=endpoint();const r=await fetch(url+(method==='GET'?'?ref='+encodeURIComponent(branch):''),{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+process.env.GITHUB_TOKEN,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined,cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok){if(r.status===409||r.status===422)throw new StoreError('Concurrent update. Please retry.',409);throw new StoreError('GitHub storage is unavailable. Check repository access and API limits.')}return r.json()}
async function snapshot(){if(github()){const d=await gh('GET');if(d.encoding!=='base64'||!d.content)throw new StoreError('Directory file is missing or too large.');return {state:decode(JSON.parse(Buffer.from(d.content,'base64').toString('utf8'))),sha:d.sha as string}}if(process.env.VERCEL)throw new StoreError('Live site requires GitHub storage.');return {state:decode(JSON.parse(await readFile(file,'utf8'))),sha:''}}
export async function readState(){return (await snapshot()).state}
let queue:Promise<unknown>=Promise.resolve();
export function mutate<T>(change:(state:State)=>T):Promise<T>{const operation=async()=>{for(let attempt=0;attempt<5;attempt++){const {state,sha}=await snapshot(),result=change(state),text=encode(state);if(github()){try{await gh('PUT',{message:'Update directory data [skip vercel]',content:Buffer.from(text).toString('base64'),sha,branch:endpoint().branch});return result}catch(e){if(e instanceof StoreError&&e.status===409&&attempt<4)continue;throw e}}const temp=file+'.'+randomBytes(8).toString('hex')+'.tmp';await writeFile(temp,text);await rename(temp,file);return result}throw new StoreError('Directory is busy. Please retry.',409)};const result=queue.then(operation,operation);queue=result.catch(()=>{});return result}
export function consumeLimit(s:State,bucket:string,max:number,expires:number){const now=Date.now();for(const [k,v] of Object.entries(s.private.limits))if(v.expires<=now)delete s.private.limits[k];for(const [k,v] of Object.entries(s.private.sessions))if(v<=now)delete s.private.sessions[k];const current=s.private.limits[bucket];if(current&&current.count>=max)throw new StoreError('Too many requests. Please try again later.',429);s.private.limits[bucket]={count:(current?.count||0)+1,expires}}
export function fingerprint(req:Request,scope:string){const ip=process.env.VERCEL?req.headers.get('x-vercel-forwarded-for')||'unknown':'local';return createHash('sha256').update(key()).update(scope+':'+ip).digest('hex')}
